[colors.primary]
background = '#f1f2f8'
foreground = '#242529'

[colors.selection]
text = '#242529'
background = '#e2e4ee'

[colors.cursor]
text = '#f1f2f8'
cursor = '#6272a4'

[colors.normal]
black   = '#20212B'
red     = '#9b3e57'
green   = '#2b7b37'
yellow  = '#c4be31'
blue    = '#6375ac'
magenta = '#dee6ff'
cyan    = '#6272A4'
white   = '#2c2c2d'

[colors.bright]
black   = '#87888b'
red     = '#c4627c'
green   = '#51b460'
yellow  = '#d5ce3f'
blue    = '#697dbc'
magenta = '#dee6ff'
cyan    = '#aab4d5'
white   = '#f1f2f6'
