# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x000000ff
rootcolor = 0x282A36ff
bordercolor = 0xa9a9a8ff
focuscolor = 0xbd93f9ff
maximizescreencolor = 0xff79c6ff
urgentcolor = 0xFF5555ff
scratchpadcolor = 0x8be9fdff
globalcolor = 0x3f0099ff
overlaycolor = 0x990058ff
