cursor #f8f8f2
cursor_text_color #f8f8f2

foreground            #f8f8f2
background            #1b1c24
selection_foreground  #f8f8f2
selection_background  #3a3c4a
url_color             #6272a4

color0   #20212B
color1   #eb534a
color2   #6ed66e
color3   #dbd37b
color4   #7985c2
color5   #7f87a9
color6   #7686b9
color7   #abb2bf
color8   #5c6370
color9   #e0615f
color10  #86e086
color11  #e8e197
color12  #bcd2ff
color13  #6a80a5
color14  #7a7baa
color15  #ffffff
