cursor #242529
cursor_text_color #58585a

foreground            #242529
background            #f1f2f8
selection_foreground  #ffffff
selection_background  #dcdcde
url_color             #6272a4

color0   #20212B
color1   #9b3e57
color2   #2b7b37
color3   #c4be31
color4   #6375ac
color5   #dee6ff
color6   #6272A4
color7   #2c2c2d
color8   #87888b
color9   #c4627c
color10  #51b460
color11  #d5ce3f
color12  #697dbc
color13  #dee6ff
color14  #aab4d5
color15  #f1f2f6
